# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{mysql_backup}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Christian Hellsten"]
  s.date = %q{2009-11-01}
  s.description = %q{A simple backup tool for MySQL that takes a backup of all MySQL databases.}
  s.email = %q{christian.hellsten@gmail.com}
  s.executables = ["mysql_backup", "mysql_backup_install"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc",
     "README.textile"
  ]
  s.files = [
    "LICENSE",
     "README.rdoc",
     "README.textile",
     "Rakefile",
     "VERSION",
     "bin/mysql_backup",
     "bin/mysql_backup_install",
     "lib/mysql_backup.rb",
     "lib/mysql_backup/backup.rb",
     "lib/mysql_backup/install.rb",
     "lib/mysql_backup/mysql_backup.yml.example",
     "lib/mysql_backup/options.rb",
     "lib/mysql_backup/pty.rb",
     "test/helper.rb",
     "test/test_mysql_backup.rb"
  ]
  s.homepage = %q{http://github.com/christianhellsten/mysql-backup}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A backup tool for MySQL.}
  s.test_files = [
    "test/helper.rb",
     "test/test_mysql_backup.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sequel>, [">= 0"])
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<sequel>, [">= 0"])
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<sequel>, [">= 0"])
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

